Changer MoCIGovernor
money-on-chain/main-RBTC-contract pull request #60
Opened 2021-06-22 18:09 UTC by mulonemartin

2021-06-22 18:43 UTC, pmprete approved these changes
👍

2021-06-25 13:59 UTC, pmprete approved these changes
👍

2021-09-03 13:43 UTC, pmprete requested changes
Change solidity pragma

2021-09-03 13:43 UTC, pmprete commented on contracts/changers/governor/ProxyAdminIGovernorChanger.sol
> +pragma solidity 0.5.8;
We are using 0.5.17 now
```suggestion
pragma solidity ^0.5.8;
```

2021-09-03 13:43 UTC, pmprete commented on contracts/changers/governor/UpgradeDelegatorIGovernorChanger.sol
> +pragma solidity 0.5.8;
```suggestion
pragma solidity ^0.5.8;
```

2022-05-11 23:41 UTC, azboyzranch approved these changes

2023-06-21 18:18 UTC, closed without merging